# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('pan_number', models.IntegerField(blank=True,
                                                   null=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'),
                                                     ('FEMALE', 'female'),
                                                     ('OTHER', 'other')],
                                            max_length=10)),
                ('birth_date', models.DateField(blank=True,
                                                null=True)),
                ('address', models.CharField(blank=True,
                                             max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(blank=True,
                                                null=True)),
                ('state', models.CharField(max_length=20)),
                ('mobile_number', models.IntegerField(blank=True,
                                                      null=True)),
                ('profile_pic', models.FileField(blank=True,
                                                 null=True,
                                                 upload_to='images')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
