# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pan_number',
        ),
    ]
